image:
  repository: dockerhub.azk8s.cn/thanosio/thanos

query:
    logLevel: debug

    replicaLabels: []
    stores: 
      - dnssrv+_grpc._tcp.prom-thanos-prometheus-server-thanos-grpc-headless.prome.svc

    service:
      type: NodePort
      nodePort: 30902

store:
    enabled: false
    logLevel: debug
    objstore:
        configMapName: "thanos-objstore-s3-config"
        configFileName: "s3.yml"
    grpcHeadless:
        servicePort: 10901
        annotations: {}
