apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.fullname" . }}-query-http
  annotations:
      {{ toYaml .Values.query.service.annotations | indent 4 }}
  labels:
      app.kubernetes.io/name: {{ template "thanos.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ .Values.query.name }}
      helm.sh/chart: {{ include "thanos.chart" . }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.query.service.type }}
  ports:
    - name: http
      port: {{ .Values.query.service.servicePort }}
      targetPort: http
      protocol: TCP
    {{- if .Values.query.service.nodePort }}
      nodePort: {{.Values.query.service.nodePort }}
    {{- end }}
  selector:
      app.kubernetes.io/name: {{ template "thanos.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ .Values.query.name }}
