{{- if .Values.store.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.fullname" . }}-store
  labels:
      app.kubernetes.io/name: {{ template "thanos.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ .Values.store.name }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.store.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "thanos.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ .Values.store.name }}
  template:
    metadata:
      labels:
          app.kubernetes.io/name: {{ template "thanos.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/component: {{ .Values.store.name }}
          {{- if .Values.store.podLabels }}
          {{ toYaml .Values.store.podLabels | nindent 8 }}
          {{- end }}
    spec:
      containers:
        - name: {{ template "thanos.name" . }}-store
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
              - store
              - --log.level={{ .Values.store.logLevel }}
              - --objstore.config-file=/etc/config/{{ .Values.store.objstore.configFileName }}
          ports:
              - name: http
                containerPort:  10902
                protocol: TCP
              - name: grpc
                containerPort: 10901
                protocol: TCP
          volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          resources:
            {{- toYaml .Values.query.resources | nindent 12 }}
      volumes:
          - name: config-volume
            configMap:
                name: {{ .Values.store.objstore.configMapName }}

      {{- with .Values.query.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.query.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.query.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
