# Default values for thanos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
image:
  repository: thanosio/thanos
  tag: master-2019-12-14-bec86666
  pullPolicy: IfNotPresent

query:
    name: "thanos-query"
    replicaCount: 1

    logLevel: "debug"

    podLables: {}

    replicaLabels: []
    stores: []

    service:
      type: ClusterIP
      annotations: {}
      labels: {}
      servicePort: 10902
      nodePort: 0

    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    nodeSelector: {}

    tolerations: []

    affinity: {}

store:
    enabled: false
    name: "thanos-store"

    logLevel: "debug"

    replicaCount: 1
    podLables: {}

    objstore:
        configFileName: ""
        configMapName: ""

    grpcHeadless:
        servicePort: 10901
        annotations: {}

    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    nodeSelector: {}

    tolerations: []

    affinity: {}
